### PR TITLE
Support ImageMagick 7+ 

### LINKED ISSUE #33: Support ImageMagick 7+ via RMagick 4.1+
https://github.com/rmagick/rmagick

> ImageMagick Version 6.7.7 or later (6.x.x). Version 7 has beta support in version 4.1.0.rc2 (#256). You can get ImageMagick from https://imagemagick.org.

### PR DESCRIPTION
**Pull request by barockok**
Resolves #33

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @barockok ! 

Can you update the PR so that both ImageMagick 6 and ImageMagick 7 are tested in the GHA builds? This is because not everyone wants to build ImageMagick 7 manually.

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Add Ubuntu text matrix to test both IM 6 and 7

**Comment by ronaldtse** [comment]
Thanks @barockok !

**Comment by ronaldtse** [comment]
Seems that there’s an issue with building?

**Comment by barockok** [comment]
> Seems that there’s an issue with building?

yeah, seems some API is deprecated in image magick `6.9.11`,  I use `6.9.10` instead. all should be resolves now.

**Comment by ronaldtse** [comment]
@barockok we also want to test against the current available packages -- not everyone is open to building libvips and ImageMagick from source. Can you add a matrix step that it installs from packages (Ubuntu and macOS)? Thanks.

**Comment by ronaldtse** [comment]
Merging this first.

**Pull request merged**
